ARG NODE_ENV=development

FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=${NODE_ENV}
RUN apk add --no-cache python3 \
    && corepack enable \
    && yarn global add tsx \
    && yarn global add pm2

EXPOSE 17280
CMD ["/bin/sh", "/app/bootstrap.sh"]
