import express, { type Router } from 'express';

/** Public path of the privacy policy page (Google Play listing links here). */
export const PRIVACY_POLICY_PATH = '/privacy';

const LAST_UPDATED = '2026-09-17';

const PAGE_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Agentiz — Privacy Policy</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         max-width: 760px; margin: 0 auto; padding: 32px 20px 64px; color: #1f2328; line-height: 1.6; }
  h1 { font-size: 1.6rem; margin-bottom: 0.2em; }
  h2 { font-size: 1.15rem; margin-top: 2em; }
  .updated { color: #57606a; font-size: 0.9rem; margin-bottom: 2em; }
  ul { padding-left: 1.3em; }
  a { color: #0969da; }
</style>
</head>
<body>
<h1>Agentiz — Privacy Policy</h1>
<p class="updated">Last updated: ${LAST_UPDATED}</p>

<p>Agentiz ("the app") is a companion client for the Agentiz task and code-agent management
platform. It is provided to users of a specific Agentiz deployment by that deployment's operator,
and is not distributed as a public consumer product. This page describes what data the app and its
backend process.</p>

<h2>Data we collect</h2>
<ul>
  <li><strong>Account credentials.</strong> Sign-in uses an account created for you by your
    organization's Agentiz administrator. We do not offer public self-registration.</li>
  <li><strong>Push notification token.</strong> To deliver notifications (new tasks, comments,
    approvals, run results) the app registers a Firebase Cloud Messaging token with the backend,
    together with the app version and a device name you can see in your device settings.</li>
  <li><strong>Task and project content.</strong> Tasks, comments, attachments (files or photos you
    upload), and code-agent run results you create or that are shared with you within your
    organization's projects.</li>
  <li><strong>Basic diagnostic information.</strong> Standard web server logs (IP address,
    timestamp, requested endpoint) generated by any HTTP request to the backend.</li>
</ul>

<h2>How this data is used</h2>
<p>Collected data is used solely to operate the app: authenticating you, showing your organization's
tasks and runs, and delivering push notifications you are eligible to receive. We do not use it for
advertising, and we do not sell or rent it to third parties.</p>

<h2>Data sharing</h2>
<p>Data is shared only with the infrastructure necessary to run the service: your organization's own
Agentiz backend (operated by your organization, not by a third party), and Google's Firebase Cloud
Messaging, used solely to transport push notifications to your device.</p>

<h2>Data retention and deletion</h2>
<p>Task, project and account data is retained for as long as your organization keeps its Agentiz
deployment and your account active, and is governed by your organization's own data retention
practices. A push token is removed automatically once it is no longer deliverable (for example, after
an app reinstall) and can also be removed by disabling notifications in the app. To request deletion
of your account or data, contact your organization's Agentiz administrator.</p>

<h2>Children's privacy</h2>
<p>Agentiz is a workplace tool intended for use by adult employees and contractors of an
organization. It is not directed at children, and we do not knowingly collect data from children.</p>

<h2>Changes to this policy</h2>
<p>If this policy changes, the "Last updated" date above will be revised accordingly.</p>

<h2>Contact</h2>
<p>Questions about this policy or about data processed by a specific Agentiz deployment should be
directed to that deployment's administrator.</p>

</body>
</html>`;

/**
 * Mounted on the root Express app, like the Worker API: a Google Play / App Store listing links
 * to this URL directly and must reach it with no admin session, so it cannot sit behind
 * `adminizerMiddlewares`'s `/dashboard` prefix or its auth.
 */
export function createPrivacyPolicyRouter(): Router {
  const router = express.Router();
  router.get('/', (_req, res) => {
    res.type('html').send(PAGE_HTML);
  });
  return router;
}
